---
- name: Install Mysql Client
  ansible.builtin.apt:
    name: "mysql-client-{{ mysql_client_version }}"
    state: present
    update_cache: yes

- name: Install Mysql Server
  ansible.builtin.apt:
    name: "mysql-server-{{ mysql_server_version }}"
    state: present
    

- name: Enabled Mysql Server
  ansible.builtin.systemd_service:
    daemon_reload: true
    enabled: true
    state: started
    name: "{{ item }}"
  loop:
  - mysql
  - nginx